using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;


public class PopupEventManager : MonoBehaviour
{
    // Controls Menus and Popups UI generated by events

    [Header("Reference")]
    private GameManager gameManager;
    private StatsManager statsManager;
    private TerminalTextManager terminalTextManager;

    [Header("Popup Menu and Options")]
    public GameObject popUpMenu;
    public GameObject eventTextBox;
    public GameObject continueButton;
    public GameObject yesButton;
    public GameObject noButton;
    public EventManager eventManager;
    public bool isPopUpActive = false;
    private TextToDisplayEvents eventObject;

    private void Awake()
    {
        gameManager = GameObject.Find("GameManager").GetComponent<GameManager>();
        statsManager = GameObject.Find("StatsManager").GetComponent<StatsManager>();
        terminalTextManager = GameObject.Find("TerminalTextManager").GetComponent<TerminalTextManager>();

        Debug.Log("TODO TO DO : display tooltip on the contine/yes/no button to info about changes when relevant (when there are any costs)");
    }

    private void FixedUpdate()
    {
        if (isPopUpActive)
        {
            // pause game when popup is active
            gameManager.StopTimePause();
            gameManager.DisableOrEnableAllTermianlButtonsInteractable(false); // make buttons not interactable
        }
    }

    public void SetUpPopup(TextToDisplayEvents displayValue)
    {
        eventObject = displayValue;
        // set up values for each option continue/yes/no
        eventTextBox.GetComponent<TextMeshProUGUI>().text = eventObject.eventText;
        if (eventObject.popUpMenuOption == popUpMenuOptions.continueOnly)
        {
            SetUpContinueYesNoTooltip(gameManager.continueOptionText, eventObject);
            SetUpGenericEvent();
        }
        else
        {
            SetUpContinueYesNoTooltip(gameManager.yesOptionText, eventObject);
            SetUpContinueYesNoTooltip(gameManager.noOptionText, eventObject);
            SetUpYesAndNoEvent();
        }
        popUpMenu.SetActive(true);
        isPopUpActive = true;
    }

    private void SetUpContinueYesNoTooltip(TextToDisplay existingValue, TextToDisplayEvents updatedValue)
    {
        // set up the dynamic tooltip for popup events (based on which event is being displayed)
        Debug.Log("setting up for: " + existingValue.name + " for the event " + updatedValue.name);
        existingValue.energyCellCost = updatedValue.energyCellCost;
        existingValue.waterCost = updatedValue.waterCost;
        existingValue.nitrogenCost = updatedValue.nitrogenCost;
        existingValue.oxygenCost = updatedValue.oxygenCost;
        existingValue.carbonDioxdeCost = updatedValue.carbonDioxdeCost;
        existingValue.hydrogenCost = updatedValue.hydrogenCost;
        existingValue.seedsCost = updatedValue.seedsCost;
        existingValue.plantsCost = updatedValue.plantCost;
        existingValue.methaneCost = updatedValue.methaneCost;
        existingValue.chemicalsCost = updatedValue.chemicalsCost;
        existingValue.robotCost = updatedValue.robotCost;
        existingValue.copperWireCost = updatedValue.copperWireCost;
        existingValue.metalCost = updatedValue.metalCost;
        existingValue.deadBatteryCost = updatedValue.deadBatteryCost;

    }
    private void SetUpYesAndNoEvent()
    {
        // set up menu with yes and no options
        continueButton.SetActive(false);
        yesButton.SetActive(true);
        noButton.SetActive(true);
    }

    private void SetUpGenericEvent()
    {
        // set up menu with just a continue button
        continueButton.SetActive(true);
        yesButton.SetActive(false);
        noButton.SetActive(false);
    }
    public void ContinueButton()
    {
        Debug.Log("PRESSED CONTINUE");
        StartCoroutine(ClosePopUpMenu());
    }

    public void YesButton()
    {
        Debug.Log("PRESSED YES");
        StartCoroutine(ClosePopUpMenu());
    }

    public void NoButton()
    {
        Debug.Log("PRESSED NO");
        StartCoroutine(ClosePopUpMenu());
    }

    public IEnumerator ClosePopUpMenu()
    {
        // close popup menu, restart time, apply event stats, display terminal text
        gameManager.StartGameFromPause(); // restarts time
        gameManager.DisableOrEnableAllTermianlButtonsInteractable(true); // make buttons not interactable

        popUpMenu.SetActive(false);
        isPopUpActive = false;

        yield return null;

        TriggerEventTextWithStatsUpdate(eventObject);
    }

    public void TriggerEventTextWithStatsUpdate(TextToDisplayEvents displayValue)
    {
        // display the termainl text and update 
        terminalTextManager.startWriteText(displayValue.eventTerminalText); // write a summary to terminal for records
        statsManager.UpdateEventValues(displayValue);
    }
}
